In [87]:
import random
from numpy.random import randint
from numpy.linalg import solve, inv
import numpy as np
a = np.array([[1, 2, 3], [3, 4, 6.7], [5, 9.0, 5]])
print(a)

a.transpose()
import array
array([[ 1. ,  3. ,  5. ],
       [ 2. ,  4. ,  9. ],
       [ 3. ,  6.7,  5. ]])
inv(a)
array([[-2.27683616,  0.96045198,  0.07909605],
       [ 1.04519774, -0.56497175,  0.1299435 ],
       [ 0.39548023,  0.05649718, -0.11299435]])
b =  np.array([3, 2, 1])
print(b)

solve(a, b)  # solve the equation ax = b
array([-4.83050847,  2.13559322,  1.18644068])
"import random"
c = random;(3, 3) * 20  # create a 3x3 random matrix of values within [0,1] scaled by 20 c
array([[  3.98732789,   2.47702609,   4.71167924],
       [  9.24410671,   5.5240412 ,  10.6468792 ],
       [ 10.38136661,   8.44968437,  15.17639591]])
np.dot(a, c)  # matrix multiplication
print(c)


[[1.  2.  3. ]
 [3.  4.  6.7]
 [5.  9.  5. ]]


TypeError: 'module' object is not callable